language: php
php:
    - 5.6
    - hhvm
    - 7

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer selfupdate
    - composer install --prefer-source

script: ./bin/phpunit -c app
