Ekreative\AppsBundle\Entity\App:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        file:
            type: string
            length: 255
            nullable: true
        version:
            type: string
            length: 255
            nullable: true
        comment:
            type: string
            length: 255
            nullable: true
        qrcode:
            type: string
            length: 500
            nullable: true
        date:
            type: datetime

    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: type
        type: string
        length: 255
    discriminatorMap:
        android: Ekreative\AppsBundle\Entity\AndroidApp
        ios: Ekreative\AppsBundle\Entity\IosApp


    lifecycleCallbacks:
       postPersist: [ upload ]
    repositoryClass: Ekreative\AppsBundle\Entity\Repository\AppsRepository
