Ekreative\AppsBundle\Entity\Folder:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        date:
            type: datetime

    inheritanceType: SINGLE_TABLE
    discriminatorColumn:
        name: type
        type: string
        length: 255
    discriminatorMap:
        android: Ekreative\AppsBundle\Entity\AndroidFolder
        ios: Ekreative\AppsBundle\Entity\IosFolder


    lifecycleCallbacks: {  }
    repositoryClass: Ekreative\AppsBundle\Entity\Repository\FolderRepository
