Ekreative\AppsBundle\Entity\IosFolder:
    type: entity
    table: null
    oneToMany:
      app:
        targetEntity: Ekreative\AppsBundle\Entity\IosApp
        mappedBy: folder
    repositoryClass: Ekreative\AppsBundle\Entity\Repository\IosFolderRepository

    manyToMany:
      users:
        targetEntity: Ekreative\AppsBundle\Entity\User
        mappedBy: iosApps