Ekreative\AppsBundle\Entity\User:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    uniqueConstraints:
        username_idx:
          columns: [ username ]

    fields:
        name:
            type: string
            length: 255
        username:
            type: string
            length: 255
        password:
            type: string
            length: 255
        salt:
            type: string
            length: 255
        email:
            type: string
            length: 255
            nullable: true
        date:
            type: datetime
        lastLogin:
            nullable: true
            type: datetime
    manyToMany:
      androidApps:
        targetEntity: Ekreative\AppsBundle\Entity\AndroidFolder
        inversedBy: users
      iosApps:
        targetEntity: Ekreative\AppsBundle\Entity\IosFolder
        inversedBy: users
