ekreative_apps:
    resource: "@EkreativeAppsBundle/Resources/config/routing.yml"
    prefix:   /

ekreative_trademen_admin:
    resource: "@EkreativeAppsBundle/Controller/"
    type:     annotation
    prefix:   /