# app/config/security.yml
security:
    firewalls:
        secured_area:
            pattern: ^/folder*
            http_basic:
               provider: in_memory         

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: super, roles: 'ROLE_ADMIN' }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    access_control:
        - { path: ^/folder*, roles: ROLE_ADMIN }
        # Include the following line to also secure the /admin path itself
        # - { path: ^/admin$, roles: ROLE_ADMIN }
     