ekreative_apps_index:
    path:     /
    defaults: { _controller: EkreativeAppsBundle:Main:index }    
 

ekreative_apps_folders:
    resource: "@EkreativeAppsBundle/Resources/config/routing/folder.yml"
    prefix:   /folder
    
ekreative_apps_android:
    resource: "@EkreativeAppsBundle/Resources/config/routing/android.yml"
    prefix:   /folder/android
    
ekreative_apps_ios:
    resource: "@EkreativeAppsBundle/Resources/config/routing/ios.yml"
    prefix:   /folder/ios

ekreative_apps:
    resource: "@EkreativeAppsBundle/Resources/config/routing/app.yml"
    prefix:   /app


ekreative_gcmtest:
    path:     /gcmtest
    defaults: { _controller: EkreativeAppsBundle:Gcm:index }
ekreative_ios_app_install:
    path:     /install/ios/{token}
    defaults: { _controller: EkreativeAppsBundle:Ios:install }
ekreative_android_app_install:
    path:     /install/android/{id}
    defaults: { _controller: EkreativeAppsBundle:Android:install }
