parameters:
    ekreative_apps.aws_key: ''
    ekreative_apps.aws_secret: ''
    ekreative_apps.aws_region: ''
    ekreative_apps.amazon_s3.base_url: ''
    
services:
  
    ekreative_apps.twig.bilty_extension:
        class: Ekreative\AppsBundle\Twig\BitlyExtension
        arguments: [@RukbatBitly]
        tags:
            - { name: twig.extension }  
  
    ekreative_apps.amazon_s3:
            class: Aws\S3\S3Client
            factory_class: Aws\S3\S3Client
            factory_method: factory
            arguments:
              -
                key: %ekreative_apps.aws_key%
                secret: %ekreative_apps.aws_secret%
                region: %ekreative_apps.aws_region%
        
    ekreative_apps.file_uploader:
            class: Ekreative\AppsBundle\Upload\FileUploader
            arguments: [ @file_storage_filesystem ]
        