parameters:
#    ekreative_apps.example.class: Ekreative\AppsBundle\Example

services:
#    ekreative_apps.example:
#        class: %ekreative_apps.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
